Ulatina.PruebaProyecto/Ulatina.PruebaProyecto/Controllers/ParametrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ulatina.PruebaProyecto.Models;

namespace Ulatina.PruebaProyecto.Controllers

{
    public class ParametrosController : Controller
    {
        // GET: Parametros
        public ActionResult Index()
        {
            var items = new List<ParametroMvc>
            {
                //var items = fooRepository.GetAll();
                //return View(items);
                new ParametroMvc() { Codigo = 1, Descripcion = "Item 1", Valor = "123" },
                new ParametroMvc() { Codigo = 1212, Descripcion = "Item 2", Valor = "1234" },
                new ParametroMvc() { Codigo = 4124, Descripcion = "Item 3", Valor = "12345" }
            };
            return View(items);
        }
        public ActionResult Editar(int Codigo)
        {

            return View();
        }
    }
}

Ulatina.PruebaProyecto/Ulatina.PruebaProyecto/Views/Parametros/Editar.cshtml
@{
    ViewBag.Title = "Reporte Articulo Perdido";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Ulatina.PruebaProyecto/Ulatina.PruebaProyecto/Views/Parametros/Index.cshtml
@using Ulatina.Selectos.Proyecto.UI.Models

@using GridMvc.Html

@model List<ParametroMvc>

@{
    ViewBag.Title = "Parámetros";
}
<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8"></div>
    <div class="col-md-4">
        @Html.ActionLink("Agregar", "Agregar", "Parametros", new { area = "" }, new { @class = "navbar-brand" })
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        @Html.Grid(Model).Columns(columns =>
   {
       columns.Add()
            .Encoded(false)
            .Sanitized(false)
            .SetWidth(30)
            .RenderValueAs(d =>
            @<b>
                @Html.ActionLink(
                    linkText: "Editar",
                    actionName: "Editar",
                    controllerName: "Parametros",
                    routeValues: new
                    {
                        Codigo = d.Codigo
                    },
                    htmlAttributes: null)
            </b>);
       columns.Add(p => p.Descripcion).Titled("Descripcion").SetWidth(110);
       columns.Add(p => p.Valor).Sortable(true);
   }).WithPaging(2)
    </div>

</div>